CREATE SCHEMA `bai`
  DEFAULT CHARACTER SET utf8;

USE 'bai';

CREATE TABLE USER_PROFILE (
  id              INTEGER NOT NULL AUTO_INCREMENT,
  login           VARCHAR(255) UNIQUE,
  last_login_date DATETIME,
  password        VARCHAR(255),
  IS_ACTIVE       BOOLEAN,
  PRIMARY KEY (id)
);

CREATE TABLE MESSAGE (
  id       INTEGER NOT NULL AUTO_INCREMENT,
  CONTENT  VARCHAR(555),
  OWNER_ID INTEGER,
  PRIMARY KEY (id)
);

ALTER TABLE MESSAGE ADD CONSTRAINT messageOwnerId FOREIGN KEY (OWNER_ID) REFERENCES USER_PROFILE (id);

CREATE TABLE ALLOWED_MESSAGE (
  id         INTEGER NOT NULL AUTO_INCREMENT,
  USER_ID    INTEGER,
  MESSAGE_ID INTEGER,
  PRIMARY KEY (id)
);